FROM openjdk:11
ADD target/RegistrationProductOwner-0.0.1-SNAPSHOT.jar receiver-registration.jar
EXPOSE 8084
ENTRYPOINT ["java","-jar","receiver-registration.jar"]                                            
