package com.stackroute.recipient.domain;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor

public class Recipient {
    /*Receipient Id's will be AutoGenerated*/
    @Id
    private String id;
    private String name;
    @Transient private String email;
    @Transient private String password;
    private long phoneNumber;
    @Transient private String role;
    @Transient private int operation;

}
